Add Code for Agent Connection History Data
racker/salus-telemetry-ambassador pull request #100
Opened 2020-09-23 06:47 UTC by shabd67

# Resolves

[SALUS-796](https://jira.rax.io/browse/SALUS-796)

# What

Envoy Connection History 

# Depends on

https://github.com/racker/salus-telemetry-model/pull/154

2020-09-28 02:00 UTC, jjbuchan reviewed
@GeorgeJahad @itzg are you guys happy with this staying in ambassador?  It would mean adding an api controller to ambassador as well.

2020-09-28 13:33 UTC, itzg commented
> are you guys happy with this staying in ambassador? It would mean adding an api controller to ambassador as well.

Yes, even though it's a new facet to add to the ambassador, it seems like the appropriate microservice to own the API.

2020-09-28 13:39 UTC, itzg commented on src/main/java/com/rackspace/salus/telemetry/ambassador/services/EnvoyRegistry.java
> +      AgentHistory agentHistory = agents.get(0);
Tracking more than one connection seems so abnormal that I am proposing [over here](https://github.com/racker/salus-telemetry-model/pull/154#discussion_r495121684) that it be constrained unique by envoy ID and an optional one entry be retrieved here. EnvoyRegistry even [disallows attachment of the same envoy ID](https://github.com/racker/salus-telemetry-ambassador/blob/0d4fe76cf110f5a32de4975565004f44f7d31e1b/src/main/java/com/rackspace/salus/telemetry/ambassador/services/EnvoyRegistry.java#L180-L188).

2020-09-28 15:27 UTC, jjbuchan commented on src/main/java/com/rackspace/salus/telemetry/ambassador/services/EnvoyRegistry.java
> +      AgentHistory agentHistory = agents.get(0);
That sounds better

2020-09-28 17:51 UTC, itzg requested changes

2020-09-28 17:51 UTC, itzg commented on src/main/java/com/rackspace/salus/telemetry/ambassador/web/model/AgentHistoryOutput.java
> +  private String disconnectedAt;
Can declare these as `Instant` to avoid the `toString` and null checking in AgentHistoryConversionService

2020-09-28 17:51 UTC, itzg commented on src/main/java/com/rackspace/salus/telemetry/ambassador/services/AgentHistoryConversionService.java
> +  public AgentHistoryOutput convertToOutput(AgentHistory agentHistory)  {
At least a simple unit test would be good

2020-09-28 17:51 UTC, itzg commented on src/main/java/com/rackspace/salus/telemetry/ambassador/services/AgentHistoryService.java
> +  public Optional<AgentHistory> getAgentHistoryForTenant(String tenantId, String envoyId) {
Method name doesn't match the intent / parameters.

2020-09-28 17:51 UTC, itzg commented on src/main/java/com/rackspace/salus/telemetry/ambassador/services/AgentHistoryService.java
> +  public Optional<AgentHistory> getAgentHistoryForResource(String tenantId, String resourceId) {
Same as https://github.com/racker/salus-telemetry-model/pull/154/files#r496113848

2020-09-28 17:51 UTC, itzg commented on src/main/java/com/rackspace/salus/telemetry/ambassador/services/EnvoyAmbassadorService.java
> +                                  MeterRegistry meterRegistry, AgentHistoryRepository agentHistoryRepository) {
Since you introduced `AgentHistoryService` you should use that in place of `AgentHistoryRepository`. Otherwise, there doesn't seem to be much value added with `AgentHistoryService`.

2020-09-28 17:51 UTC, itzg commented on src/main/java/com/rackspace/salus/telemetry/ambassador/services/EnvoyAmbassadorService.java
> +    private void addEnvoyConnectionClosedTime(String tenantId, String envoyId)  {
...and this method could now go in `AgentHistoryService`

2020-09-28 17:51 UTC, itzg commented on src/main/java/com/rackspace/salus/telemetry/ambassador/services/EnvoyRegistry.java
> +      AgentHistoryRepository agentHistoryRepository) {
Doesn't seem to be used anymore

2020-09-28 17:51 UTC, itzg commented on src/main/java/com/rackspace/salus/telemetry/ambassador/web/controller/AgentHistoryController.java
> +  public AgentHistoryOutput getAgentHistoryForTenant(
See https://github.com/racker/salus-telemetry-model/pull/154#discussion_r496128911

2020-09-28 17:51 UTC, itzg commented on src/main/java/com/rackspace/salus/telemetry/ambassador/services/AgentHistoryService.java
> +public class AgentHistoryService {
Please add a simple unit test for each method.

2020-09-29 01:49 UTC, jjbuchan requested changes
Some small comments.  Those + tests will be good.

2020-09-29 01:49 UTC, jjbuchan commented on src/main/java/com/rackspace/salus/telemetry/ambassador/web/model/AgentHistoryOutput.java
> +  private String tenantId;
tenantId can be annotated with `@JsonView(View.Admin.class)`.  There's no need to send it for customer requests as they can only request their own tenant.

2020-09-29 01:49 UTC, jjbuchan commented on src/main/java/com/rackspace/salus/telemetry/ambassador/services/EnvoyAmbassadorService.java
> +            .setId(UUID.randomUUID());
You don't need to save an id yourself.  `repository.save` will allocate one since it's annotated with `@GeneratedValue`

2020-09-29 01:49 UTC, jjbuchan commented on src/main/java/com/rackspace/salus/telemetry/ambassador/web/controller/AgentHistoryController.java
> +
This endpoint should also return all agent history for the tenant if neither `envoyId` or `resourceId` are provided.

2020-09-29 01:49 UTC, jjbuchan commented on src/main/java/com/rackspace/salus/telemetry/ambassador/web/controller/AgentHistoryController.java
> +    if(!StringUtils.isEmpty(resourceId))  {
We should add some validation to ensure both `envoyId` and `resourceId` are not both set, otherwise it'll currently return the history for resource.

An `IllegalArgumentException` should be thrown if they are both set.

2020-09-29 02:02 UTC, jjbuchan commented on src/main/java/com/rackspace/salus/telemetry/ambassador/services/AgentHistoryConversionService.java
> +    BeanUtils.copyProperties(agentHistory, agentHistoryOutput);
Rather than doing this here, a lot of our other api objects have a constructor that accepts the db object as a parameter.  It might be better to follow that standard for this.

e.g. if you look at `ResourceDTO.java` or `ZoneDTO.java` you'll see:

```
public ResourceDTO(Resource resource, String envoyId) {
    this.id = resource.getId();
    ...

public ZoneDTO(Zone zone) {
    this.name = zone.getName();
    ...
```
You would have
```
public AgentHistoryOutput(AgentHistory history) {
    ...
```

I'm not against using `BeanUtils` but having the logic in the other class would be good.

---

I'm guessing you copied the `convertToOutput` way from `DetailedMonitorOutput`.  That's from the early days of all these services and something we've never got around to cleaning up,

2020-09-29 13:50 UTC, itzg requested changes
Looking good overall. Just a few little things left.

2020-09-29 13:50 UTC, itzg commented on src/main/java/com/rackspace/salus/telemetry/ambassador/services/AgentHistoryService.java
> +    final String tenantId = GrpcContextDetails.getCallerTenantId();
I don't see a unit test for this one. [There's actually bit of a trick to testing with GrpcContextDetails](https://github.com/racker/salus-telemetry-ambassador/blob/0d4fe76cf110f5a32de4975565004f44f7d31e1b/src/test/java/com/rackspace/salus/telemetry/ambassador/services/EnvoyAmbassadorServiceTest.java#L106); however, I would recommend passing in these three as parameters so that knowledge of `GrpcContextDetails` can remain within `EnvoyAmbassadorService`.

2020-09-29 13:50 UTC, itzg commented on src/main/java/com/rackspace/salus/telemetry/ambassador/services/AgentHistoryService.java
> +    }
Sorry I missed this before. A warning log and error metric would be good when closing an envoy connection that wasn't in DB.

2020-09-29 13:50 UTC, itzg commented on src/main/java/com/rackspace/salus/telemetry/ambassador/web/controller/AgentHistoryController.java
> +      return PagedContent.fromPage(agentHistoryService.getAgentHistoryForTenantAndResource(tenantId, resourceId, pageable)).map(AgentHistoryDTO::new);
A couple of well placed newlines will reduce long lines like this and improve readability. Reviewing more of our PRs and code you will see some stylistic patterns, such as placing stream operators on a new line with its leading dot:

```suggestion
    return PagedContent.fromPage(
        agentHistoryService.getAgentHistoryForTenantAndResource(tenantId, resourceId, pageable)
    )
        .map(AgentHistoryDTO::new);
```

2020-09-29 13:50 UTC, itzg commented on src/test/java/com/rackspace/salus/telemetry/ambassador/services/AgentHistoryServiceTest.java
> +    assertThat(agentHistoryOptional.get().getZoneId(), equalTo("z-1"));
You could put these into a private method, like `assertExpectedAgentHistory` and then call it in tests below

2020-09-29 13:50 UTC, itzg commented on src/test/java/com/rackspace/salus/telemetry/ambassador/web/controller/AgentHistoryControllerTest.java
> +        .thenReturn(Optional.of(agentHistory));
Be sure to always pair every `when` with a `verify`. In this case, it is necessary to verify that your controller code passed the request parameters correctly to the mocked service.

2020-09-29 13:50 UTC, itzg commented on src/test/java/com/rackspace/salus/telemetry/ambassador/web/controller/AgentHistoryControllerTest.java
> +    String envoyId = RandomStringUtils.randomAlphabetic(8);
Use the randomized values that podam put in `agentHistory` which then keeps your test self-consistent.

2020-09-29 13:50 UTC, itzg commented on src/test/java/com/rackspace/salus/telemetry/ambassador/web/controller/AgentHistoryControllerTest.java
> +    String resourceId = RandomStringUtils.randomAlphabetic(8);
Same x 2 as above

2020-09-29 13:50 UTC, itzg commented on src/test/java/com/rackspace/salus/telemetry/ambassador/web/controller/AgentHistoryControllerTest.java
> +    String tenantId = RandomStringUtils.randomAlphabetic(8);
and here

2020-09-29 13:50 UTC, itzg commented on src/test/java/com/rackspace/salus/telemetry/ambassador/web/controller/AgentHistoryControllerTest.java
> +        .thenReturn(Optional.of(agentHistory));
and in this case you need a `verifyNoInteractions(agentHistoryService)`

2020-09-29 17:29 UTC, jjbuchan requested changes

2020-09-29 17:29 UTC, jjbuchan commented on src/main/java/com/rackspace/salus/telemetry/ambassador/services/AgentHistoryService.java
> +    agentHistoryError = Counter.builder("agent-history-save-failed").tag(MetricTags.SERVICE_METRIC_TAG,"AgentHistoryService");
Just a note...

I'm now noticing we have various different styles for metric names throughout the services.  some `camelCase`, some `snake_case`, and some `kebab-case`.  It would be good if we could pick one and stick with it.

You don't have to change this one here now, but it could be a good follow up to clean up these across repos.

2020-09-29 17:29 UTC, jjbuchan commented on src/main/java/com/rackspace/salus/telemetry/ambassador/services/AgentHistoryService.java
> +    agentHistoryError = Counter.builder("agent-history-save-failed").tag(MetricTags.SERVICE_METRIC_TAG,"AgentHistoryService");
I don't have much of an opinion of which format we use, but I think built-in metrics tend to use `snake_case` so maybe that's best?

2020-09-29 17:29 UTC, jjbuchan commented on src/main/java/com/rackspace/salus/telemetry/ambassador/services/AgentHistoryService.java
> +       return agentHistoryRepository.findByTenantIdAndEnvoyId(tenantId, envoyId);
@itzg I do keep wondering if this is fully "safe".  I imagine your assumption is that there will never be two envoys that have the same id?

Do we care about this failing in local dev where we could connect with a constant id numerous times?  I'm not sure how this handles those cases - whether it returns the first it sees or whether it blows up.

2020-09-29 17:29 UTC, jjbuchan commented on src/main/java/com/rackspace/salus/telemetry/ambassador/services/AgentHistoryService.java
> +    if(!agent.isEmpty()) {
very nitpicky... `isPresent` is the standard way to check optionals.

```suggestion
    if (agent.isPresent()) {
```

2020-09-29 17:29 UTC, jjbuchan commented on src/main/java/com/rackspace/salus/telemetry/ambassador/web/controller/AgentHistoryController.java
> +  public AgentHistoryController(AgentHistoryService agentHistoryService)  {
Also missing `@Autowired` here

2020-09-29 17:29 UTC, jjbuchan commented on src/main/java/com/rackspace/salus/telemetry/ambassador/web/controller/AgentHistoryController.java
> +      throw new IllegalArgumentException("EnvoyId and ResourceId both cannot be not-null");
```suggestion
      throw new IllegalArgumentException("envoyId and resourceId cannot both be set");
```

Avoiding the double-negative makes it a little clearer to me.

2020-09-29 17:29 UTC, jjbuchan commented on src/main/java/com/rackspace/salus/telemetry/ambassador/web/controller/AgentHistoryController.java
> +              new NotFoundException(
I think it makes more sense to return the empty list instead of throwing an exception.  It'll make the response consistent when using either a non-existent resourceId or envoyId

2020-09-29 17:29 UTC, jjbuchan commented on src/main/java/com/rackspace/salus/telemetry/ambassador/web/model/AgentHistoryDTO.java
> +  @JsonView(View.Admin.class)
`id` shouldn't need this annotation.

This also reminds me that having an endpoint for `@GetMapping("/tenant/{tenantId}/agent-history/{agentHistoryId}")` would actually be useful, where `{agentHistoryId}` relates to this id.

2020-09-29 17:29 UTC, jjbuchan commented on src/test/java/com/rackspace/salus/telemetry/ambassador/services/AgentHistoryServiceTest.java
> +    currentAgentHistory = agentHistory;
```suggestion
    currentAgentHistory = agentHistoryRepository.save(agentHistory);
```

It doesn't appear to be matter much for these tests but fyi, this will allow the auto-generated id to be used later on when asserting things against `currentAgentHistory` fields.

2020-09-29 17:29 UTC, jjbuchan commented on src/test/java/com/rackspace/salus/telemetry/ambassador/web/controller/AgentHistoryControllerTest.java
> +  }
It could be good to add some cases for when no history is returned.  e.g. related to my previous comment, you would have a test that if no history is found for tenantId & envoyId it would return an empty list and not a bad request.

2020-09-29 18:07 UTC, itzg commented on src/main/java/com/rackspace/salus/telemetry/ambassador/services/AgentHistoryService.java
> +  public AgentHistoryService(AgentHistoryRepository agentHistoryRepository,
It's actually not required for constructor autowiring; however, I like it being there to clarify the intent.

2020-09-29 18:08 UTC, itzg commented on src/main/java/com/rackspace/salus/telemetry/ambassador/services/AgentHistoryService.java
> +    agentHistoryError = Counter.builder("agent-history-save-failed").tag(MetricTags.SERVICE_METRIC_TAG,"AgentHistoryService");
Agreed and yes, I think snake_case seems to be prevailing format for built-in

2020-09-29 18:23 UTC, itzg requested changes

2020-09-29 18:23 UTC, itzg commented on src/main/java/com/rackspace/salus/telemetry/ambassador/services/AgentHistoryService.java
> +      agentHistoryError.tags(MetricTags.OPERATION_METRIC_TAG, "addAgentHistory", MetricTags.EXCEPTION_METRIC_TAG,"error occurred while saving agent history")
I think `EXCEPTION_METRIC_TAG` is meant to be the exception class name, not the message. I'd prefer you leave out `EXCEPTION_METRIC_TAG` case since there's not an exception involved. As mentioned before, metric tags directly translate into the time-series database series cardinality -- arbitrary error messages have unbounded cardinality :O

2020-09-29 18:23 UTC, itzg commented on src/main/java/com/rackspace/salus/telemetry/ambassador/services/AgentHistoryService.java
> +      log.warn("unable to find connection history with tenantId= {} and envoyId= {} ",tenantId, envoyId);
Since you'll be in here for line below, we capitalize the first letter of log messages and no spaces in the `field={}` part 
```suggestion
      log.warn("Unable to find connection history with tenantId={} and envoyId={} ",tenantId, envoyId);
```

2020-09-29 18:23 UTC, itzg commented on src/main/java/com/rackspace/salus/telemetry/ambassador/web/controller/AgentHistoryController.java
> +              new NotFoundException(
That's logical to me

2020-09-29 18:23 UTC, itzg commented on src/test/java/com/rackspace/salus/telemetry/ambassador/services/AgentHistoryServiceTest.java
> +  private void assertExpectedAgentHistory(Optional<AgentHistory> agentHistoryOptional) {
I meant for you to add calls to this in testGetAgentHistoryForTenantAndResource and testGetAgentHistoryForTenant

2020-09-30 13:20 UTC, shabd67 commented on src/main/java/com/rackspace/salus/telemetry/ambassador/web/controller/AgentHistoryController.java
> +              new NotFoundException(
have changed accordingly.

2020-09-30 13:29 UTC, shabd67 commented on src/test/java/com/rackspace/salus/telemetry/ambassador/services/AgentHistoryServiceTest.java
> +  private void assertExpectedAgentHistory(Optional<AgentHistory> agentHistoryOptional) {
@itzg , I didn't get you by this "I meant for you to add calls to this in testGetAgentHistoryForTenantAndResource and testGetAgentHistoryForTenant". Can you elaborate?

2020-09-30 13:38 UTC, itzg commented on src/test/java/com/rackspace/salus/telemetry/ambassador/services/AgentHistoryServiceTest.java
> +    assertThat(result.getTotalElements(), equalTo(1L));
This is the kind of change mentioned in https://github.com/racker/salus-telemetry-ambassador/pull/100/files#r496946445
```suggestion
    assertThat(result.getTotalElements(), equalTo(1L));
    assertExpectedAgentHistory(Optional.of(result.getContent().get(0));
```

2020-09-30 13:56 UTC, itzg requested changes

2020-09-30 13:56 UTC, itzg commented on src/main/java/com/rackspace/salus/telemetry/ambassador/services/AgentHistoryService.java
> +    if(!agent.isPresent()) {
It seems like this logic is flipped. If switching to `isPresent` I think it should be
```suggestion
    if(agent.isPresent()) {
```

A unit test should have caught this.

2020-09-30 13:56 UTC, itzg commented on src/main/java/com/rackspace/salus/telemetry/ambassador/services/AgentHistoryService.java
> +    agentHistoryError = Counter.builder("agent_history_save_failed").tag(MetricTags.SERVICE_METRIC_TAG,"AgentHistoryService");
I just noticed the prefix "agent_history" is redundant with the`SERVICE_METRIC_TAG`. Perhaps you could use `MetricNames.SERVICE_OPERATION_FAILED`.

2020-09-30 13:56 UTC, itzg commented on src/main/java/com/rackspace/salus/telemetry/ambassador/web/controller/AgentHistoryController.java
> +        return PagedContent.ofSingleton(null);
Hmm, I guess we need a `PageContent.empty()` method since `ofSingleton(null)` will produce an awkward response that looks like an element count of 1 but the one element will be null.

For now can just do
```suggestion
        return PagedContent.fromPage(Page.empty());
```

2020-09-30 13:56 UTC, itzg commented on src/test/java/com/rackspace/salus/telemetry/ambassador/web/controller/AgentHistoryControllerTest.java
> +        .andExpect(jsonPath("$.content[0]").doesNotExist());
Hmm, regarding my comment above about `PagedContent.ofSingleton(null)` I would have expected this expectation to fail.

2020-09-30 14:03 UTC, shabd67 commented on src/main/java/com/rackspace/salus/telemetry/ambassador/services/AgentHistoryService.java
> +    if(!agent.isPresent()) {
have to write a test case for that.

2020-09-30 14:08 UTC, itzg reviewed
assertExpectedAgentHistory usage looks good. Ping a re-review when you have the "ifPresent" unit test added.

2020-09-30 14:51 UTC, itzg approved these changes
A re-review from @jjbuchan would be good before merging.

2020-10-01 17:07 UTC, shabd67 commented
@jjbuchan , please review it once you are free.

2020-10-01 23:26 UTC, jjbuchan commented on src/main/java/com/rackspace/salus/telemetry/ambassador/services/AgentHistoryService.java
> +       return agentHistoryRepository.findByTenantIdAndEnvoyId(tenantId, envoyId);
@itzg interested in your thoughts here.

2020-10-01 23:40 UTC, jjbuchan approved these changes

2020-10-01 23:49 UTC, itzg commented on src/main/java/com/rackspace/salus/telemetry/ambassador/services/AgentHistoryService.java
> +       return agentHistoryRepository.findByTenantIdAndEnvoyId(tenantId, envoyId);
Except in unit tests in the envoy, the envoyId is not a constant value -- in fact, it's better to think of it as a session ID since it gets regenerated on every attach/re-attach:

https://github.com/racker/salus-telemetry-envoy/blob/28079e15d33619112c5cac4a94808f56ed9edf19/ambassador/connection.go#L206

That makes me start to wonder if some of the envoyId collision checking in EnvoyRegistry is pointless since it is regenerated on every attachment.

2020-10-01 23:56 UTC, jjbuchan commented on src/main/java/com/rackspace/salus/telemetry/ambassador/services/AgentHistoryService.java
> +       return agentHistoryRepository.findByTenantIdAndEnvoyId(tenantId, envoyId);
Thanks for the link.  I knew it wasn't constant but wasn't sure if it was unique enough if we potentially were tracking a large history of old ones.

I didn't realize we were using uuids there; thought I'd seen something else before.

2020-10-05 07:02 UTC, merged