Convert simple api requests to db requests
racker/salus-telemetry-ambassador pull request #97
Opened 2020-09-09 12:37 UTC by rohitsngh27

# Resolves
https://jira.rax.io/browse/SALUS-1014

# What
Convert simple api requests to db requests

# How
Created a method to get from DB and convert it to DTO

# How to test
This can be tested by unit test cases

2020-09-09 16:11 UTC, itzg requested changes
Ambassador purposely wasn't using database access before, so a couple of extra changes are needed:

- `application-dev.yml` needs spring data jpa bits [like this](https://github.com/racker/salus-telemetry-monitor-management/blob/f9891401f3124dda9d0d82fb0cedbac047b905ef/src/main/resources/application-dev.yml#L21-L33)
- a `DatabaseConfig` needs to be added [like this one](https://github.com/racker/salus-telemetry-monitor-management/blob/f9891401f3124dda9d0d82fb0cedbac047b905ef/src/main/java/com/rackspace/salus/monitor_management/config/DatabaseConfig.java#L22-L26)

2020-09-09 16:11 UTC, itzg commented on src/main/java/com/rackspace/salus/telemetry/ambassador/services/AgentInstallsListener.java
> +import org.springframework.data.domain.Range.Bound;
unused import?

2020-09-09 16:11 UTC, itzg commented on src/test/java/com/rackspace/salus/telemetry/ambassador/services/ResourceLabelsServiceTest.java
> + * Copyright 2019 Rackspace US, Inc.
Double check your copyright profile's template. The year should be filled by a template variable `$today.year`.

2020-09-09 16:56 UTC, rohitsngh27 commented on src/test/java/com/rackspace/salus/telemetry/ambassador/services/ResourceLabelsServiceTest.java
> + * Copyright 2019 Rackspace US, Inc.
I haven't added any template in IntelliJ yet. Is there a specific one?

2020-09-09 18:03 UTC, jjbuchan commented on src/test/java/com/rackspace/salus/telemetry/ambassador/services/ResourceLabelsServiceTest.java
> + * Copyright 2019 Rackspace US, Inc.
This should help - https://github.com/Rackspace-Segment-Support/salus-docs-internal/issues/9

However, mine never updates the year for existing files like Geoff's does even though it uses that template.  I've not spent any time to troubleshoot it yet since as my branch isn't behind on commits everything should work well enough.

2020-09-09 18:06 UTC, itzg commented on src/test/java/com/rackspace/salus/telemetry/ambassador/services/ResourceLabelsServiceTest.java
> + * Copyright 2019 Rackspace US, Inc.
To double check I found the link to that KB at the very end of https://github.com/Rackspace-Segment-Support/salus-docs-internal/blob/master/guides/onboarding-salus.md#ide-setup

I have the "Update Copyright" option enabled in git commit settings in IntelliJ:

![image](https://user-images.githubusercontent.com/988985/92636646-5484d480-f29d-11ea-8738-188964f2603c.png)

2020-09-09 18:07 UTC, jjbuchan reviewed
Current changes looks good.  Just needs a little cleanup and the changes Geoff mentioned.

2020-09-09 18:07 UTC, jjbuchan commented on src/main/java/com/rackspace/salus/telemetry/ambassador/config/RestClientsConfig.java
> +//  }
cleanup required

2020-09-09 18:07 UTC, itzg commented on src/test/java/com/rackspace/salus/telemetry/ambassador/services/ResourceLabelsServiceTest.java
> + * Copyright 2019 Rackspace US, Inc.
Wow, that image was big

2020-09-10 17:46 UTC, itzg approved these changes
Please also update and PR [this diagram](https://github.com/racker/salus-docs/blob/master/overview/Salus%20system%20components.drawio.png) to add the new system dependency on MySQL from Ambassador. (It's a PNG, but can be edited with [draw.io (aka diagrams.net)](https://app.diagrams.net/)

2020-09-10 17:46 UTC, itzg commented on src/main/resources/application-dev.yml
> +    platform: mysql
Just a note that you'll need to coordinate with devops to have [the helm chart](https://github.com/Rackspace-Segment-Support/helm-salus-ambassador) changed to include the new MySQL config and proxy container. Please create a Jira issue with "devops" label and bring it up in next planning meeting.

2020-09-10 18:22 UTC, jjbuchan requested changes

2020-09-10 18:22 UTC, jjbuchan commented on src/main/java/com/rackspace/salus/telemetry/ambassador/services/AgentInstallsListener.java
> +            .orElseThrow(() -> new NotFoundException("Could find find agent install for given resource and agent type")));
Typo in this message.  Should be `Could not find agent`?

2020-09-10 18:28 UTC, jjbuchan requested changes

2020-09-10 18:28 UTC, jjbuchan commented on pom.xml
>              <version>7.2.1.RELEASE</version>
The dependency on `salus-telemetry-agent-catalog-management` farther up can be removed and relates to https://github.com/racker/salus-telemetry-agent-catalog-management/pull/43/files#r486549905

2020-09-10 18:53 UTC, itzg approved these changes

2020-09-10 18:55 UTC, jjbuchan requested changes

2020-09-10 18:55 UTC, jjbuchan commented on src/main/java/com/rackspace/salus/telemetry/ambassador/services/AgentInstallsListener.java
> +            () -> new NotFoundException("Could find find agent for given resource and agent type"));
Typo in the message. `Could find find`

2020-09-10 19:09 UTC, jjbuchan approved these changes

2020-09-10 19:12 UTC, merged