Updated MetricRouter to use UniversalMetricFrame
racker/salus-telemetry-ambassador pull request #99
Opened 2020-09-17 14:48 UTC by rohitsngh27

# Resolves
https://jira.rax.io/browse/SALUS-1004?

# What
Update MetricRouter to use UniversalMetricFrame schema

# How
Changes is MetricRouter class to use new UniversalMetricFrameSchema

# How to test
This can be tested via unit test cases

2020-09-17 15:43 UTC, itzg requested changes
Just a couple minor changes

2020-09-17 15:43 UTC, itzg commented on src/main/java/com/rackspace/salus/telemetry/ambassador/services/MetricRouter.java
> +            .setAccountType(UniversalMetricFrame.AccountType.MANAGED_HOSTING)
@rohitsngh27 can you write up a Jira issue to remind us to enhance the account type logic here? The initial accounts we'll migrate are `MANAGED_HOSTING`, so we're good for a little while. In that Jira issue you could note that maybe we should look at the prefix of `tenantId` to determine the account type.

2020-09-17 15:43 UTC, itzg commented on src/main/java/com/rackspace/salus/telemetry/ambassador/services/MetricRouter.java
> +            .setDeviceName(nameTagValue.getName())
Actually `nameTagValue.getName()` is `measurementName`, so not a valid entry here. This one will actually need to be enriched downstream, so leave it unset unless protobuf complains and set to an empty string.

2020-09-17 15:43 UTC, itzg commented on src/main/java/com/rackspace/salus/telemetry/ambassador/services/MetricRouter.java
> +            log.warn("Failed to Avro encode avroMetric={} original={}", universalMetricFrame,
Can get rid of Avro mention and also make generic with
```suggestion
            log.warn("Failed to encode metricFrame={} from={}", universalMetricFrame,
```

2020-09-17 15:43 UTC, itzg commented on src/main/java/com/rackspace/salus/telemetry/ambassador/services/MetricRouter.java
> +    }
Nice

2020-09-17 15:43 UTC, itzg commented on src/test/resources/MetricRouterTest/testRouteMetric.json
> +  "deviceName": "cpu",
I'm guessing protobuf will leave out this field given my request above. [From docs](https://developers.google.com/protocol-buffers/docs/proto3#json) it sounds like it should:

> If a field has the default value in the protocol buffer, it will be omitted in the JSON-encoded data by default to save space.

2020-09-17 15:46 UTC, rohitsngh27 commented on src/main/java/com/rackspace/salus/telemetry/ambassador/services/MetricRouter.java
> +            .setAccountType(UniversalMetricFrame.AccountType.MANAGED_HOSTING)
Sure

2020-09-18 13:15 UTC, itzg requested changes
Just a spelling change

2020-09-18 13:15 UTC, itzg commented on src/main/java/com/rackspace/salus/telemetry/ambassador/services/MetricRouter.java
> +        Map<String, String> resourceLables = resourceLabelsService.getResourceLabels(tenantId, resourceId);
```suggestion
        Map<String, String> resourceLabels = resourceLabelsService.getResourceLabels(tenantId, resourceId);
```

2020-09-18 13:15 UTC, itzg commented on src/main/java/com/rackspace/salus/telemetry/ambassador/services/MetricRouter.java
> +                "No resource lables are being tracked for tenant={} resource={}",
```suggestion
                "No resource labels are being tracked for tenant={} resource={}",
```

2020-09-18 14:57 UTC, itzg approved these changes

2020-09-21 10:57 UTC, merged